name: Lint Code

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install uv
      - run: uv sync
      - run: SKIP=sphinx-apidoc,sphinx-build-html uv run pre-commit run --all-files